name: Build and Deploy To Dev
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - ".github/"
      - "test/"

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get short sha of the commit
        id: shorten_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    outputs:
      dockerfile: ./Dockerfile
      image-name: gcswdev/gcsw-app
      app-name: gcsw-dev
      image-tag: "${{ steps.shorten_sha.outputs.short_sha }}"

  build:
    needs: vars
    name: "Build and Push to Heroku"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: "sebastiancotrina16@gmail.com"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ needs.vars.outputs.app-name }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
