name: Build and Deploy To Dev
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - ".github/"
      - "test/"

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get short sha of the commit
        id: shorten_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
    outputs:
      dockerfile: ./Dockerfile
      image-name: gcswdev/gcsw-app
      app-name: gcsw-dev
      image-tag: "${{ steps.shorten_sha.outputs.short_sha }}"

  build:
    needs: vars
    name: "Build and Push to Heroku"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL_DEV }}
          username: ${{ secrets.ACR_USERNAME_DEV }}
          password: ${{ secrets.ACR_PWD_DEV }}

      - name: Build Docker Image
        run: |
          docker build -t  ${{ needs.vars.outputs.image-name }}:${{ needs.vars.outputs.image-tag }} -f ${{ needs.vars.outputs.dockerfile }} .
          docker tag ${{ needs.vars.outputs.image-name }} registry.heroku.com/${{ needs.vars.outputs.app-name }}/web:${{ needs.vars.outputs.image-tag }}

      - name: Push Docker Image to Heroku Container Registry
        run: |
          heroku container:login
          docker push registry.heroku.com/${{ needs.vars.outputs.app-name }}/web:${{ needs.vars.outputs.image-tag }}

      - name: Deploy to Heroku
        run: |
          heroku container:release web --app ${{ needs.vars.outputs.app-name }}
